# -*- coding: utf-8 -*-
"""Bird_Species.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q2BJ6XpO__B7V64o2jzUpGOjpchZ0pzz

**Project Name - Bird Species Observation Analysis**

**Project Summary**

The goal of this project is to perform exploratory data analysis (EDA) on bird species observation data to understand patterns in species distribution and activity across different habitats. The analysis focuses on identifying how factors such as habitat type, seasonal variations, environmental conditions (temperature, humidity, wind, and sky), and observation characteristics influence bird presence and behavior. The project aims to extract meaningful insights to support data-driven decisions in biodiversity conservation, habitat management, and ecological monitoring.

**Key Steps:**

**Data Collection and Cleaning:**

The dataset contains bird observation details including species name, habitat type (forest and grassland), location, date and time of observation, environmental factors (temperature, humidity, wind, sky), and behavioral attributes.

The data was cleaned by:


*   Checking for missing values and handling them appropriately (removal or
    imputation)
*   Removing duplicate records to ensure data accuracy

*   Converting columns such as Date and Time into proper formats
*   Standardizing categorical fields like habitat type, sky condition, and wind description

*   Creating new features such as Month, Year, and Season for better analysis
*   Ensuring correct data types and consistency across all columns

**Data Visualization**

Various visualization techniques were used to analyze patterns and relationships:
*   Bar charts for analyzing bird activity across seasons and environmental conditions (sky, wind)
*   Clustered column charts for comparing bird observations across different habitats and years

*   Line charts for identifying monthly and temporal trends in bird activity
*   Scatter plots for studying relationships between environmental factors (temperature, humidity) and bird count
*   Donut charts for visualizing habitat-wise distribution (forest vs grassland)
These visualizations helped uncover patterns, trends, and correlations in bird species distribution, seasonal activity, and environmental impact.

**Insights**

The analysis revealed several key insights:

*   Bird activity is higher during the Monsoon season compared to Summer within the available data period
*   June shows peak bird observations, indicating increased activity during mid-season


*   Moderate temperature ranges (around 20–30°C) are associated with higher bird activity
*   Clear and partly cloudy sky conditions tend to have more bird sightings compared to overcast conditions


*   Low wind conditions are more favorable for bird observations and activity

*   Bird distribution varies across habitats, enabling comparison between forest and grassland ecosystems
*   The dataset covers only May to July, so insights are limited to partial seasonal trends

**GitHub Link**

Problem Statement

This dataset was created to analyze bird species observations across different habitats and understand how environmental and ecological factors influence bird distribution and activity.

The problem statement highlights the need to:


*   Compare bird species distribution across different habitats (forest vs grassland)
*   Identify key environmental factors (temperature, humidity, wind, sky conditions) affecting bird activity

*   Analyze how seasonal variations influence bird presence and behavior
*   Study observation patterns such as time, distance, and detection methods

*   Provide insights for conservation planning, biodiversity monitoring, and ecological research

Understanding these patterns helps in making informed decisions for wildlife conservation, habitat management, and sustainable environmental practices.

## **Data Wrangling**
"""

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Visualization settings
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

forest = pd.read_excel('/content/Bird_Monitoring_Data_FOREST.XLSX')
grassland = pd.read_excel('/content/Bird_Monitoring_Data_GRASSLAND.XLSX')

# Import library
import pandas as pd

# Load datasets
forest = pd.read_excel('/content/Bird_Monitoring_Data_FOREST.XLSX')
grassland = pd.read_excel('/content/Bird_Monitoring_Data_GRASSLAND.XLSX')

# Add Habitat column
forest['Habitat_Type'] = 'Forest'
grassland['Habitat_Type'] = 'Grassland'

# Merge (combine) both datasets
dataset = pd.concat([forest, grassland], ignore_index=True)

# Preview data
dataset.head()

forest.columns

grassland.columns

dataset.columns

forest.shape

grassland.shape

dataset.shape

"""**Data Description**

The Bird Species Observation dataset contains structured information about bird sightings recorded across different habitats, including forests and grasslands. Each record represents a single observation and includes details related to species identification, location, time of observation, environmental conditions, and behavioral attributes.

The dataset is designed to analyze bird species distribution and understand how different factors such as habitat type, seasonal variations, and environmental conditions (temperature, humidity, wind, and sky) influence bird activity and presence. This analysis helps in identifying ecological patterns, species behavior, and key factors affecting biodiversity and habitat utilization.

Dataset Columns

Admin_Unit_Code – Code representing the administrative unit where the observation was conducted

Sub_Unit_Code – Sub-category within the administrative unit for detailed classification

Site_Name – Name of the observation site

Plot_Name – Specific plot identifier where birds were observed

Location_Type – Type of habitat (e.g., Forest, Grassland)

Habitat_Type – Added column indicating ecosystem category (Forest / Grassland)

Date – Date of observation

Start_Time / End_Time – Time duration of the observation session

Year – Year of observation (derived for analysis)

Month – Month of observation (derived for trends)

Season – Seasonal classification (Winter, Summer, Monsoon, Post-Monsoon)

Observer – Person who recorded the observation

Visit – Number of visits to the same location

Common_Name – Common name of the bird species

Scientific_Name – Scientific name of the species

Sex – Gender of the observed bird (Male/Female/Unknown)

ID_Method – Method used to identify the bird (Singing, Calling, Visual, etc.)

Distance – Distance of the bird from the observer

Flyover_Observed – Indicates if the bird was flying overhead (True/False)

Temperature – Recorded temperature during observation

Humidity – Recorded humidity percentage

Sky – Sky condition (Clear, Cloudy, Overcast, etc.)

Wind – Wind condition during observation

Disturbance – External disturbance affecting observation

Initial_Three_Min_Cnt – Number of birds observed in the first three minutes (used as Bird Count for analysis)

**Box Plot**

**Box Plot of Bird Count**

The box plot represents the distribution of bird observations (Initial_Three_Min_Cnt) in the dataset.

It helps to understand:

Median Bird Count – The central value of bird observations across all records

Interquartile Range (IQR) – The spread of the middle 50% of bird counts, showing typical observation ranges

Minimum & Maximum Counts – The overall range of bird observations recorded

Outliers – Observations with unusually high or low bird counts

From the visualization, most bird observations fall within a moderate range, while a few instances with very high counts appear as outliers, indicating areas or conditions with unusually high bird activity.
"""

# Box Plot of Bird Count

import matplotlib.pyplot as plt
import seaborn as sns

# Plot
plt.figure(figsize=(8,5))
sns.boxplot(x=dataset['Initial_Three_Min_Cnt'])

# Title and labels
plt.title('Box Plot of Bird Count')
plt.xlabel('Bird Count')

plt.show()

"""Most bird observations are concentrated within a moderate range (middle 50% of the data).

The median bird count lies near the center of the box, indicating a relatively balanced distribution of observations.

The spread (IQR) shows moderate variation in bird activity across different observations and conditions.

A few observations appear as outliers, representing unusually high bird counts (possibly in highly active habitats or favorable conditions) or very low counts.

Overall, the dataset shows some variability in bird activity but is not extremely skewed, indicating consistent observation patterns across the dataset.
"""

dataset['Date'] = pd.to_datetime(dataset['Date'])  # ensure date format

dataset['Month'] = dataset['Date'].dt.month_name()

plt.figure(figsize=(10,6))
dataset.groupby('Month')['Initial_Three_Min_Cnt'].sum().plot(kind='line', marker='o')

plt.title('Monthly Bird Activity')
plt.xlabel('Month')
plt.ylabel('Bird Count')

plt.show()

# Make sure Date is in datetime format
dataset['Date'] = pd.to_datetime(dataset['Date'])

# Create Season column
def get_season(month):
    if month in [12,1,2]:
        return 'Winter'
    elif month in [3,4,5]:
        return 'Summer'
    elif month in [6,7,8,9]:
        return 'Monsoon'
    else:
        return 'Post-Monsoon'

dataset['Season'] = dataset['Date'].dt.month.apply(get_season)

plt.figure(figsize=(8,5))
sns.barplot(x='Season', y='Initial_Three_Min_Cnt', data=dataset)

plt.title('Bird Activity by Season')
plt.xlabel('Season')
plt.ylabel('Bird Count')

plt.show()

habitat_data = dataset.groupby('Habitat_Type')['Initial_Three_Min_Cnt'].sum()

plt.figure(figsize=(6,6))
plt.pie(habitat_data, labels=habitat_data.index, autopct='%1.1f%%')

plt.title('Bird Distribution by Habitat')
plt.show()

plt.figure(figsize=(8,5))
sns.barplot(x='Sky', y='Initial_Three_Min_Cnt', data=dataset)

plt.title('Bird Activity by Sky Condition')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,5))
sns.barplot(x='Wind', y='Initial_Three_Min_Cnt', data=dataset)

plt.title('Bird Activity by Wind Condition')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,5))
plt.scatter(dataset['Humidity'], dataset['Initial_Three_Min_Cnt'])

plt.title('Humidity vs Bird Activity')
plt.xlabel('Humidity')
plt.ylabel('Bird Count')

plt.show()

plt.figure(figsize=(6,5))

yearly = dataset.groupby('Year')['Initial_Three_Min_Cnt'].sum()
yearly.plot(kind='bar')

plt.title('Yearly Bird Trends')
plt.xlabel('Year')
plt.ylabel('Bird Count')

plt.show()

"""**Conclusion**

This analysis examined bird species observations across forest and grassland habitats, identifying key patterns in activity and distribution. The results indicate higher bird activity during the monsoon season, with environmental factors such as temperature, weather conditions, and wind significantly influencing observations.

As the dataset is limited to May–July, the findings represent partial seasonal trends. Overall, habitat type and environmental conditions are the primary factors affecting bird activity and distribution.

These insights can support biodiversity conservation efforts, habitat management strategies, and ecological research by helping identify favorable conditions for bird activity and areas that may require focused conservation attention.
"""